server.port=8080
spring.application.name=多源异构数据融合与统计检验分析平台V1.0
spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB
spring.thymeleaf.cache=false
spring.web.resources.cache.period=0
